projeto/core/urls.py
from django.urls import path
from projeto.core import views as v

app_name = 'core'

urlpatterns=[
    path('', v.index, name='index'),
]

projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views as v

app_name = 'estoque'

urlpatterns = [
    path('', v.estoque_entrada_list, name='estoque_entrada_list'),
    path('<int:pk>/', v.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
    path('add-row/', v.add_row_estoque_items_hx, name='add_row_estoque_items_hx'),
    path('produto/preco/', v.produto_preco, name='produto_preco'),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

app_name = 'produto'

urlpatterns = [
    path('', v.produto_list, name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
]

projeto/core/models.py
from django.db import models

# Create your models here.

class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now=False,
        auto_now_add=True,
        )
    modified = models.DateTimeField(
        'modificado em',
        auto_now= True,
        auto_now_add=False,
    )

    class Meta:
        abstract = True

projeto/estoque/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from projeto.core.models import TimeStampedModel
from projeto.produto.models import Produto

MOVIMENTO = (
    ('e', 'Entrada'),
    ('s', 'Saída')
)

class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(User, on_delete=models.CASCADE)
    nf = models.PositiveIntegerField('Nota Fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        time = self.created.strftime('%d/%m/%Y')
        return f'{self.pk} - {time}'

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_entrada_detail', kwargs={'pk': self.pk})

    def nf_formated(self):
        return str(self.nf).zfill(4)

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(
        Estoque,
        on_delete=models.CASCADE,
        related_name='estoques'
    )
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField()
    saldo = models.PositiveIntegerField()

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return f'{self.pk} - {self.estoque.pk} - {self.produto}'

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy

class Produto(models.Model):
    importado = models.BooleanField(default=False)
    ncm = models.CharField('NCM', max_length=8)
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('Preço', max_digits=7, decimal_places=2)
    estoque = models.IntegerField('Estoque Atual')
    estoque_minimo = models.PositiveIntegerField('Estoque Mínimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

projeto/estoque/forms.py
from django import forms
from .models import Estoque, EstoqueItens


class EstoqueForm(forms.ModelForm):
    class Meta:
        model = Estoque
        fields = '__all__'


class EstoqueItensForm(forms.ModelForm):
    class Meta:
        model = EstoqueItens
        fields = '__all__'

projeto/produto/forms.py
from django import forms
from .models import Produto

class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

projeto/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

projeto/estoque/views.py
from django.shortcuts import render, resolve_url, redirect
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse

from .models import Estoque, EstoqueItens
from .forms import EstoqueForm, EstoqueItensForm


def estoque_entrada_list(request):
    template_name = 'estoque_entrada_list.html'
    objects = Estoque.objects.filter(movimento='e')
    context = {'object_list': objects}
    return render(request, template_name, context)

def estoque_entrada_detail(request, pk):
    template_name = 'estoque_entrada_detail.html'
    obj = Estoque.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def estoque_entrada_add(request):
    template_name = 'estoque_entrada_form.html'
    if request.method == 'POST':
        form = EstoqueForm(request.POST)
        item_estoque_formset = inlineformset_factory(
            Estoque,
            EstoqueItens,
            form=EstoqueItensForm,
            extra=1,
        )
        formset = item_estoque_formset(request.POST)
        if form.is_valid() and formset.is_valid():
            form = form.save()
            formset.instance = form
            formset.save()
            url = 'estoque:estoque_entrada_detail'
            return HttpResponseRedirect(reverse(url, args=(form.pk,)))
        else:
            context = {'form': form, 'formset': formset}
            return render(request, template_name, context)
    else:
        form = EstoqueForm()
        item_estoque_formset = inlineformset_factory(
            Estoque,
            EstoqueItens,
            form=EstoqueItensForm,
            extra=1,
        )
        formset = item_estoque_formset()
        context = {'form': form, 'formset': formset}
        return render(request, template_name, context)

def produto_preco(request):
    template_name = 'hx/produto_preco_hx.html'
    url = request.get_full_path()
    print('url', url)
    print(url.split('-'))
    item = url.split('-')[1]
    produto_pk = list(request.GET.values())[0]
    produto = Product.objects.get(pk=produto_pk)

    context = {'produto': produto, 'item': item[0]}
    return render(request, template_name, context)

def add_row_estoque_items_hx(request):
    template_name = 'hx/row_estoque_items_hx.html'
    form = EstoqueItensForm()
    context = {'form': form}
    return render(request, template_name, context)

projeto/produto/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from .models import Produto
from .forms import ProdutoForm

def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    context = {'object_list': objects}
    return render(request, template_name, context)

def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

def produto_add(request):
    template_name = 'produto_form.html'
    return render(request, template_name)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm

projeto/core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://static.djangoproject.com/img/favicon.6dbf28c0650e.ico">
    <title>Sistema de Estoque</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <!-- Fonte Awesome -->
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.2/css/fontawesome.min.css" integrity="sha384-X8QTME3FCg1DLb58++lPvsjbQoCT9bp3MsUU3grbIny/3ZwUJkRNO8NPW6zqzuW9" crossorigin="anonymous">


    <style>
      body {
        margin-top: 60px;
      }
      .ok {
        color: green;
      }
      .no {
        color: red;
      }
    </style>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.0"></script>

    {% block css %} {% endblock css %}
  </head>
  <body>
    {% include "includes/nav.html" %}

    <div class="container">
      {% block content %} {% endblock content %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->
{% load static %}

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/0a65f28876.js" crossorigin="anonymous"></script>
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'jquery.formset.js' %}"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

projeto/core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">EMPRESA</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'produto:produto_list' %}">Produtos</a>
          </li>
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Estoque
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a></li>
                    <li><a class="dropdown-item" href="#">Saída</a></li>
                  </ul>
                </li>
              </ul>
            </div>
        </ul>
      </div>
    </div>
  </nav>

projeto/core/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="p-2 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1>Bem-Vindo!</h1>
        <p>Sistema de Controle de Vendas</p>
    </div>
</div>

{% endblock content %}

projeto/estoque/templates/estoque_entrada_detail.html
{% extends "base.html" %}

{% block content %}

<br>
<a href="{% url 'estoque:estoque_entrada_list' %}">
    <button type="button" class="btn btn-outline-primary">
        <span class="fa-solid fa-arrow-left-to-line"></span>
        Voltar para lista de Entradas
    </button>
</a>
<hr>
<br>

<h4><i class="fa-regular fa-file-lines"></i> Registro de Entrada de estoque: </h4>
<h2> {{ object }}</h2>

<div class="col-sm-6">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">NF</th>
                <td>{{ object.nf_formated }}</td>
            </tr>
            <tr>
                <th class="text-right">Data</th>
                <td>{{ object.created }}</td>
            </tr>
            <tr>
                <th class="text-right">Funcionário</th>
                <td>{{ object.funcionario.first_name }}</td>
            </tr>
        </tbody>
    </table>
</div>
<br>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object.estoques.all %}
            <tr>
                <td>{{ obj.produto }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.saldo }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

projeto/estoque/templates/estoque_entrada_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load bootstrap %}
{% load static %}

{% block css %}
<style>
    span.required:after {
        content: " *";
        color: red;
    }
    .form-control {
      margin: 10px;
    }
    .legend {
      border-bottom: 1px solid #e5e5e5;
    }
</style>
{% endblock css %}

{% block content %}

<!-- Botão Voltar -->
<br>
<a href="{% url 'estoque:estoque_entrada_list' %}">
    <button type="button" class="btn btn-outline-primary">
        <span class="fa-solid fa-arrow-left-to-line"></span>
        Voltar para lista de Entradas
    </button>
</a>

<hr>

<!-- Start Form -->
<div class="row">
    <div class="col-sm-6">
        <form method="POST" novalidate>
            {% csrf_token %}
            <!-- Entrada de Estoque -->
            <legend class="legend">Entrada de Estoque</legend>

            <div class="row">
                <div class="col-sm-12">
                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">
                                {% if field.field.required %}
                                    <span class="required">{{ field.label }}</span>
                                {% else %}
                                    {{ field.label }}
                                {% endif %}
                            </label>

                            {% render_field field class="form-control" %}
                            <br>

                            {% for error in field.errors %}
                                <span class="text-muted">{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    {{ formset.management_form }}
                </div>
            </div>


            <!-- Entrada de Produto dentro do Estoque -->
            <!--
            <legend class="legend">Adicionar produtos no estoque:</legend>
            -->

            <hr>

            <!-- Novo método de formulário 25/09/2022 -->
            <div class="row">
                <div class="col-sm-12">

                    <legend class="legend">Adicionar produtos no estoque:</legend>

                    <div id="estoqueitens" class="form-inline">
                        {% for form in formset %}
                            <div id="item-{{ forloop.counter0 }}" class="form-group">
                                {% render_field form.estoque data-field='estoque' %}
                                {{ form.estoque }}
                                {{ form.id }}

                                {{ form.produto.label }}
                                {% render_field form.produto class="form-control" hx-get="/estoque/produto/preco/" hx-target="#id_price" hx-swap="outerHTML" data-field='produto'%}

                                {{ form.quantidade.label }}
                                {% render_field form.quantidade class="form-control" data-field='quantidade' %}

                                {{ form.saldo.label }}
                                {% render_field form.saldo class="form-control" data-field='saldo' %}

                                {% if form.id.value %}
                                    <span
                                      class="span-is-link no ml-2 remove-row"
                                      hx-delete="{% url 'ecommerce:order_item_delete' order_item_form.id.value %}"
                                      hx-confirm="Deseja mesmo deletar o item {{order_item_form.id.value}}?"
                                      hx-target="#item-{{ forloop.counter0 }}"
                                      hx-swap="outerHTML"
                                    >
                                      <i class="fa fa-times fa-lg"></i>
                                    </span>
                                {% else %}
                                    <span class="span-is-link no ml-2" onclick="removeRow()">
                                      <i class="fa fa-times fa-lg"></i>
                                    </span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <!-- Comentado
            <div class="row">
                <div class="col-sm-12">
                    <legend style="border-bottom: 1px solid #e5e5e5">
                        Produtos
                    </legend>
                    <div id="estoque" class="form-inline">
                        {% for item_estoque_form in formset %}
                            <div id="item-{{ forloop.counter0 }}" class="form-group">
                                {{ item_estoque_form|bootstrap }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            -->

            <!-- Formulário alternativo de Produtos
            {% for form in formset %}
                <div class="inlineform">
                    {{ form }}
                    <hr>
                </div>
            {% endfor %}
            -->

            <!-- Botão -->
            <div class="row">
                <span
                    id="add-item"
                    class="btn btn-outline-primary"
                    style="margin-top: 20px;"
                    hx-get="{% url 'estoque:add_row_estoque_items_hx' %}"
                    hx-target="#estoqueitens"
                    hx-swap="beforeend"
                >
                    <i class="fa-solid fa-file-circle-plus"></i>
                    Adicionar Produto
                </span>
            </div>


<div class="row">
    <div class="col-sm-6" style="margin-top: 50px;">
        <div class="form-inline buttons">
            <button class="btn btn-success" value="Save">
                <i class="bi bi-file-plus-fill"></i>
                Salvar Entrada de Estoque
            </button>
            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">
                <i class="bi bi-x-square-fill"></i>
                Cancelar!
            </a>
        </div>
    </div>
</div>


        </form>
    </div>
</div>

{% endblock content %}

{% block js %}

<script type="text/javascript">
    $(function() {
        $('#.inlineform').formset({
            prefix: '{{ formset.prefix }}'
        });
    })
</script>

<script>

    document.body.addEventListener('htmx:configRequest, (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    });

</script>

{% endblock js%}

projeto/estoque/templates/estoque_entrada_list.html
{% extends "base.html" %}

{% block content %}

<div class="container text-center">
<br>
    <div class="row">
        <div class="col">
            <h2><i class="fa-solid fa-file"></i> Estoque de Entrada </h2>
        </div>
        <div class="col">
            <span class="pull-right">
                <a href="{% url 'estoque:estoque_entrada_add' %}">
                    <button type="button" class="btn btn-primary">
                        <span><i class="fa-solid fa-file-circle-plus"></i></span> Adicionar Entrada no Estoque
                    </button>
                </a>
            </span>
        </div>
    </div>
</div>
<br>
<br>

{% if object_list %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Registro</th>
                <th>NF</th>
                <th>Data de Entrada</th>
                <th>Funcionário</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                    </td>
                    <td>{{ object.nf_formated }}</td>
                    <td>{{ object.created }}</td>
                    <td>{{ object.funcionario.first_name }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    <br>
    <h1 class="text-center">## Sem itens na lista ##</h1>

{% endif %}

{% endblock content %}

projeto/estoque/templates/hx/produto_preco_hx.html
<input
  id="id_items-{{ item }}-preco"
  name="items-{{ item }}-preco"
  class="form-control"
  type="number"
  data-field="preco"
  value="{{ produto.preco|safe }}"
/>

projeto/estoque/templates/hx/row_estoque_items_hx.html
{% load widget_tweaks %}

<div id="item-{{ forloop.counter0 }}" class="form-group">

  <div class="form-group">
    <hr>

    <label>{{ form.produto.label }}</label>
    {% render_field form.produto class="form-control" hx-get="/estoque/produto/preco/" hx-target="#id_preco" hx-swap="outerHTML" data-field='produto' %}

    <label>{{ form.quantidade.label }}</label>
    {% render_field form.quantidade class="form-control" data-field='quantidade' %}

    <label>{{ form.saldo.label }}</label>
    {% render_field form.saldo class="form-control" data-field='saldo' %}
  </div>

  <span class="span-is-link no ml-2" onclick="removeRow()">
    <i class="fa fa-times fa-lg"></i>
  </span>

</div>

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}
<br>
<a href="{% url 'produto:produto_list' %}">
    <button type="button" class="btn btn-outline-primary">
        <span class="fa-solid fa-arrow-left-to-line"></span>
        Voltar para lista de Produtos
    </button>
</a>
<hr>

<h1>{{ object }}
    <span class="pull-right">
        <a href="{% url 'produto:produto_edit' object.pk  %}">
            <button type="button" class="btn btn-outline-success btn-sm me-md-2">
                <span class="fa-solid fa-pen-to-square"></span>
                Editar
            </button>
        </a>
    </span>
</h1>

<div class="col-sm-3">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-right">Importado</th>
                <td>
                    {% if object.importado %}
                        <i class="fa-solid fa-circle-check ok"></i>
                    {% else %}
                        <i class="fa-solid fa-circle-minus no"></i>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="text-right">NCM</th>
                <td>{{ object.ncm }}</td>
            </tr>
            <tr>
                <th class="text-right">Preço</th>
                <td>R$ {{ object.preco }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque</th>
                <td>{{ object.estoque }}</td>
            </tr>
            <tr>
                <th class="text-right">Estoque Mínimo</th>
                <td>{{ object.estoque_minimo }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block css %}
<style>
    span.required:after {
        content: " *";
        color: red;
    }
</style>
{% endblock css %}

{% block content %}
<br>
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }}</span>
                {% else %}
                    {{ field.label }}
                {% endif %}

            </label>
                {% if field.label == 'Importado' %}
                    {% render_field field %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}
            <br>
            {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-success">Cadastrar Produto</button>
</form>

{% endblock content %}

{% block js %}
<script>
  $("id_importado").removeClass("form-control");
</script>
{% endblock js %}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
    <div class="container text-center">
        <br>
        <div class="row">
            <div class="col">
                <h2><i class="fa-solid fa-file"></i> Lista de Produtos</h2>
            </div>
            <div class="col">
                <span class="pull-right">
                    <a href="{% url 'produto:produto_add' %}">
                        <button type="button" class="btn btn-primary">
                            <span><i class="fa-solid fa-file-circle-plus"></i></span> Adicionar produto
                        </button>
                    </a>
                </span>
            </div>
        </div>
    </div>
    <br>
    {% if object_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Importado</th>
                <th>NCM</th>
                <th>Produto</th>
                <th>Preço</th>
                <th class="text-center">Estoque</th>
                <th class="text-center">Estoque Mínimo</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        {% if object.importado %}
                            <i class="fa-solid fa-circle-check ok"></i>
                        {% else %}
                            <i class="fa-solid fa-circle-minus no"></i>
                        {% endif %}
                    </td>
                    <td>{{ object.ncm }}</td>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
                    </td>
                    <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                    <td class="text-center">{{ object.estoque }}</td>
                    <td class="text-center">{{ object.estoque_minimo }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="alert alert-warning">Lista VAZIA</p>
    {% endif %}

</div>

{% endblock content %}